name: Identify repositories for archival
on:
  workflow_dispatch:
    inputs:
      start_date:
        description: 'Start date (YYYY-MM-DD)'
        required: true
        type: string
      end_date:
        description: 'End date (YYYY_MM_DD)'
        required: false
        default: ''
        type: string

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  run-archival-identifier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Run archival-identifier
        id: archive
        uses: DinneK/archival-identifier-test-repo@main
        with:
          inputs:
            start_date:
              description: 'Start date (YYYY-MM-DD)'
              required: true
              type: string
            end_date:
              description: 'End date (YYYY_MM_DD)'
              required: false
              default: ''
              type: string
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
